apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgCuxBXpUOXaKToH9nsjRQOjsKEww+bBWjsqHjLyefqpvH3ZQv1YQhsnq1SPwStiD3x70drmM4X6ZgskwdkgTtZN0XGeXE3vJZowU4wO06gf8d0GnnG6kTE7xw2KNwPkEW4QUiwfQqCgLf9vHZa0uy6pUDQCT5zt3lPv4i1Kzx286aFQ34vhsue+VEzVgbhcf77zBfqh8LGauI7ElGnQXrXejgwcBOex0rfbfUMONmLjHHsQ5rOYRSEJgVpPpf+NlXO/ZaIApMEeoeQehn2fCuvATR9hjDRRrkKB0xXl3XtLrS0WNcB8eETkKWaBz6oAJbHZypCyZCfqiXxqZNorEBYrWgXMw555jrJQbg1e0slEw9CUkcDCZOEGAU/pF2PCxfbdteMPG8IO4cSrEOxOLT1TSS3NYTDt1psWR+l5xGYk/BxtVoKA+tr8JL409M/2eWMQ2PiDYgNKtsRaovUtiJzhnHXjjRR5lnPRoCLP2/44Ot5q9wrTCAubpk+0G1F2mV7xNMSgxo/l+oHHUbMZf4xE2NGuZr1bfyrsRz4acBsQeKCI1rff9iUNW8q3XtPGTKSZmHVpsPGrOSzfxzFRpN/IERFXttJfUrNGGPIhCMrmyQG78bGGgclPrmT+rP9g5jrSJtOJgzxWe4+2NcjuAv9KIsTo87v3IeZAfhUTv0VvLx6H+yhiKPig0oCbN1ekCYL8U5kMtje0wJvB4mO+e/1eIsNs/d5SKO3MTP2kMYONS2E=
    password: AgALTijIR+InNkYYWi9cGCTB9EOFWl5AIfKJ5iJtD78bAcKlmSqI8mu6+iTIfFL2zuW0WtNHlyC7BQQGED2OVA7nBAy3klL7X9Dmn5J/zfWLIN+CWDEoDJuScUSEw3rGe3vbvbFxYaclb/UkHvMRDPzSpNVEn83t5Xke0gSXsKoeq7P1Gb4Z4pczRKHJXdMu2LZT62d7zHYK8PoUsGrj8v/PRvvZUmifDD789FlPEmkmH/yh/ZEGBS+VKZeujbYR+RTWADA0c0GahR8pZx0relGQJbWGapdaXpJPiVaOtBm9DrVE6+D2MJxQdbd4Em3jGH0qO8eNIVIRTshkyK/nvx42qwZuWZfTQJCyFcKJFMckQfUt4hOoyiROLyuc4wgowdieQdVDJk4ZXx/1Sdx4P+ZZ/9WfvrHibv8bkzUbP9dZwu9hrxkMiPod64Ch0NVXVy8JUg7R41bDSnhIQ175zyLNmeHoaJLbMBEOxC/o7EhGfxUTE/sxPhThAdgCLr8xM69BIX6nUIoCw53VY7PnqKZXZLL4gMPo4BqKW8eJS9bsvwS1hm7GdXd6sllcOl8HiDLV8wwXYN6XQSwoORptPol8sMs6h297M6oY8gbolUfFzBVjE/noZA+VoJoko/3sm6gttRvvHKQ1E4wlYFRLHez3D4ruUexqZOlmst3AqH9irKuzS2OcwAFdJfys+kjPXYbZMtfuf3itp2EJh2xTSOg=
    username: AgBxBo2CrbwSwX4yP/nZAq0JySc7EjYaGycAhLPBtAVkId4CVTWNzMB2noMQrTP9Y0q7XC6PL/m4sp8TnkbqtiUpicwH83Qm736kMYhutQ8MO+dPa0CN/4DFCs0PA7NbqgPkiIkX1J2oI+yg3RmSsnRhDQpFIlUEMNhI536EfsXu9Hi/BPkDVyy8pDdsFpMfKeHlJ0o9715XD6kiuVtghGZw4zgkWee61s3GzZZESZ1aMV3rRXsdq1248Gssh8WqQW5d0ScTPfUvO95wxxdYG/8iC2Zm4y5wvEUhhE9nA4HWJJq7PTSQowf98+0H0iInO3qNZxL3t9tmiRXtIVoBpjiqzuQXKNE5gtEIQjH8uOvh0K775tBHZBcImoVl7QjzwXBYflQx5jv7GOfWZa271JCEHNGxyc6h1dqvKyRgO5wtIzhHs+u0z58fhoBp9rmNxmT0zdDK9rTHqKuaDFDUuJ+omHRyhV2/80tJQY2/3NdhHPxdTsptC1CHxSw9YL8jZz/SaDdiuL3tYNn5cnp+qVbgOaPdQzBBiAUwlUWA7tTJ9vHG/F+7KMpZ5Bftr5FVHcck2FrZc56A3k7UvhsU/wLp15EPQ6+bPdpuHZZQ3Aib8So+ByGb32+O4x7rZHNDWfYZ4SU4XSvc0e8S4GEgCJvBMvlvjWzQwoKs4c7tM4o+oqaA+nISrVqigv1NOyVVHM+7lt+1CdW1PvUVfQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque



